[package]
name = "toboggan_trajectory"
version = "0.1.0"
authors = ["Vegard Strand <vegard.stra@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { path = "../aoc" }
